# Site settings
title: The Plant
baseurl: "/the_plant" # the subpath of your site, e.g. /blog/
url: "http://eakett.ca" # the base hostname & protocol for your site
destination: dist
exclude: [Gruntfile.js, README.md, node_modules, package.json]
sass:
  style: compressed
